### ISSUE TITLE
Validar el formulario

### ISSUE THREAD

**Issue by renatojobal** [chjuca/Algoritmo-Reemplazo-Paginas#19]
- [x] Validar que no se ingresen caracteres " " (espacio). 
- [x] No permitir que el usuario aplique el algoritmos hasta que haya agregado al menos una cadena

**Comment by renatojobal** [comment]
No es tanta prioridad porque al final como dijo @chjuca , nosotros somos los que vamos a usar el proyecto

**Comment by CarlosCastillo10** [comment]
Al saber esto ni lo hacia mmvs
